import os


DEFAULT_CLOUDINARY_CLOUD_NAME = "your_cloud_name"

DEFAULT_CLOUDINARY_UPLOAD_PRESET = (
    "your_unsigned_upload_preset"
)


CLOUDINARY_CLOUD_NAME = os.getenv(
    "CLOUDINARY_CLOUD_NAME",
    DEFAULT_CLOUDINARY_CLOUD_NAME,
).strip()


CLOUDINARY_UPLOAD_PRESET = os.getenv(
    "CLOUDINARY_UPLOAD_PRESET",
    DEFAULT_CLOUDINARY_UPLOAD_PRESET,
).strip()